### PR TITLE
feature: implemented ability to set default values for file loaders, …

### PR DESCRIPTION
**Pull request by vsamofal**
…with dotenv-expand syntax

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/Nikaple/nest-typed-config/blob/main/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Related issue linked using `fixes #number`
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by vsamofal** [comment]
@Nikaple Hi, one more thing regarding default values. I'm planning to update the docs a bit over the weekend, and I think that will be fine. 

I have one more feature in mind but it will be for a bit later. 

Right now, we make the resolution and, after that, do merge, but ideally, we should do merge first and then resolution it will be more accurate behavior, and performance will also be better, for my use cases at least. 

I'm implementing a kind of [PROFILES](https://mkyong.com/spring-boot/spring-boot-profile-based-properties-and-yaml-example/
) in spring

**Comment by vsamofal** [comment]
@Nikaple Hi, any concerns merging this?

**Comment by Nikaple** [comment]
Certainly, I find the code to be fine. As per our previous conversation, you mentioned your intention to make some adjustments to the documentation during the weekend. I am still waiting for the updated version 😆

**Comment by vsamofal** [comment]
Hi @Nikaple , docs updated

**Pull request merged**
