### PR TITLE
feat: can select not existing config

### PR DESCRIPTION
**Pull request by ZanMinKian**
Suppose I have code below:
```ts
export class Config {
  @IsOptional()
  @Type(() => StarterConfig)
  @ValidateNested()
  starter?: StarterConfig
}

export const ConfigModule = TypedConfigModule.forRoot({
  schema: Config,
  load: [dotenvLoader({ separator: '_' })],
})

const starterConfig = selectConfig(ConfigModule, StarterConfig)
console.log(starterConfig)
```
If `.env` is an empty file, it will throw an error because of it `can only select existing config`. This is an unnecessary limitaion. Because of this limitation, I have no way to let `starter` be optional.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/Nikaple/nest-typed-config/blob/main/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [ ] Related issue linked using `fixes #number`
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

[x] Yes
[ ] No

### CODE REVIEW

**Comment by Nikaple** [comment]
Thanks for the PR! It seems unnecessary to introduce a breaking change for a minor feature like this. Could you refactor your PR to eliminate the breaking change? I'll suggest add an optional option param like this:

```ts
interface SelectConfigOptions {
  allowOptional?: boolean;
}
const selectConfig = <T, Option extends SelectConfigOptions>(
  module: DynamicModule,
  Config: ClassConstructor<T>,
  options?: Option
): Option extends { allowOptional: true } ? T | undefined : T => {
  // 
}
```

**Comment by ZanMinKian** [comment]
> Thanks for the PR! It seems unnecessary to introduce a breaking change for a minor feature like this. Could you refactor your PR to eliminate the breaking change? I'll suggest add an optional `options` param like this:
> 
> ```ts
> export interface SelectConfigOptions {
>   /**
>    * when true, allow undefined config declared with `@IsOptional()`
>    */
>   allowOptional?: boolean;
> }
> const selectConfig = <T, Option extends SelectConfigOptions>(
>   module: DynamicModule,
>   Config: ClassConstructor<T>,
>   options?: Option
> ): Option extends { allowOptional: true } ? T | undefined : T => {
>   // 
> }
> ```

IMO, optional `options` is not very good. It's difficult to use. As a developer who use this library, I don't like my code add `{ allowOptional: true }` all the time.
```ts
// 👇 Looks not good. I don't want to add `{ allowOptional: true }` all the time.
const starterConfig = selectConfig(ConfigModule, StarterConfig, { allowOptional: true })
console.log(starterConfig)
``` 

Here are my sugguestions:
1. Accept this PR in `v3.0.0`.
2. Add one more util function named `selectConfigOptional`. It's implementation looks like `selectConfig` but will not throw the error.

**Comment by Nikaple** [comment]
> As a developer who use this library, I don't like my code add { allowOptional: true } all the time.

You can just encapsulate your own function:

```ts
export const selectConfigOptional = <T, Option extends SelectConfigOptions>(
  module: DynamicModule,
  Config: ClassConstructor<T>
) => selectConfig(module, Config, { allowOptional: true });
```

In fact, `selectConfig` is only designed to be used in corner cases like `@Controller` or `WebSocketGateway()`, and I want to keep this feature as minimum as possible, and that's why I suggest to add an optional parameter. If there are more features to come in the future, we can continue to expand the `options` parameter without any breaking changes.

As for 3.0, currently there are no plans yet, as I don't want to release any major version without major features.

**Comment by Nikaple** [comment]
Closed by #82, feel free to try [v2.3.0](https://github.com/Nikaple/nest-typed-config/releases/tag/v2.3.0)!

**Pull request closed without merging**
